### ISSUE TITLE
Not yet implemented.

### ISSUE THREAD

**Issue by luckytao** [fbacchella/ipmilib#3]
java.lang.IllegalArgumentException: Not yet implemented.
	at com.veraxsystems.vxipmi.coding.security.CipherSuite.getAuthenticationAlgorithm(CipherSuite.java:104)
	at com.veraxsystems.vxipmi.coding.commands.session.OpenSession.preparePayload(OpenSession.java:170)
	at com.veraxsystems.vxipmi.coding.commands.session.OpenSession.encodeCommand(OpenSession.java:143)

dell的服务器获取没问题，浪潮的服务器获取报错

**Comment by fbacchella** [comment]
In english please, with a better description.
